---
# install archive to local bin dir

- name: Download binary to dest and make executable
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest | default(localbin_dir + '/' + item.name) }}"
    checksum: "{{ item.checksum | default(omit) }}"
    mode: "{{ item.mode | default('1755') }}"
    owner: "{{ item.owner | default(localbin_user) }}"
    group: "{{ item.group | default(omit) }}"
  become: true
  become_user: "{{ localbin_user }}"
  when: not item.unpack|default(false)

- name: check if binary already installed
  command: "{{ item.dest | default(localbin_dir + '/' + item.name) }}
    {{ item.version_command | default('--version') }}"
  changed_when: false
  ignore_errors: true
  register: localbin_version_output
  when: item.unpack|default(false)

- name: install if binary not present
  block:
    - name: download archive
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.url | basename }}"
        checksum: "{{ item.checksum | default(omit) }}"

    - name: unarchive
      unarchive:
        src: "/tmp/{{ item.url | basename }}"
        dest: "{{ item.dest | default(localbin_dir) }}"
        extra_opts: "{{ item.extra_opts | default(omit) }}"
        remote_src: true
      become: true
      become_user: "{{ localbin_user }}"
  when:
    - item.unpack|default(false)
    - "( localbin_version_output is failed )
        or ( item.version not in localbin_version_output.stdout )"
